---

- name: Check if zroot zpool exists
  shell:
    cmd: |
      if [ -z $(zpool list -H -o name zroot) ]; then echo "success" > /tmp/zroot_not_exists; fi
  register: zrootcheck
  when: caution_wipe_disks == 'yes'

- name: output value of zrootcheck
  debug:
    msg: "{{ zrootcheck }}"
  when: zrootcheck is succeeded

- name: Wipe disks
  become: yes
  become_user: root
  shell:
    chdir: /root
    cmd: |
      sh -c "echo ACCEPTDATALOSS | ./mfsbsd_clean.sh zroot {{ conf_disks }}"
  register: wipe_disks
  when: caution_wipe_disks == 'yes'
  ignore_errors: false

- name: output content of wipe_disks in debug
  debug:
    msg: "{{ wipe_disks }}"
  when: caution_wipe_disks == 'yes'
