---

- name: Wipe disks
  become: yes
  become_user: root
  shell:
    cmd: |
      echo "ACCEPTDATALOSS" | /root/mfsbsd_clean.sh zroot "{{ conf_disks }}"
  #when: ansible_facts['caution_wipe_disks']|lower == 'yes'
  # condition not working!