---

- name: find success in qemu exit file
  lineinfile: 
    dest: /tmp/qemu_is_exited
    line: "success"
  check_mode: yes
  register: presence
  failed_when: presence.changed

- name: Reboot to exit rescue system
  become: yes
  become_user: root
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: pause for 120 seconds
  pause:
    seconds: 120

# need to perform check on bsd host port 22 with ultimate username
- name: Wait for the reboot and reconnect
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
    timeout: 300
  connection: local
