---

- name: Ansible version check
  any_errors_fatal: true
  import_playbook: playbooks/ansible-version.yml

- name: Connect to rescue system and download depenguin.me installer
  any_errors_fatal: true
  import_playbook: playbooks/depenguin-init.yml

- name: Install python3 in mfsbsd
  any_errors_fatal: false
  import_playbook: playbooks/install-python.yml

- name: Wipe disks if variable caution_wipe_disks is set to yes in inventory
  any_errors_fatal: true
  import_playbook: playbooks/wipe-disks.yml

- name: Connect to depenguin.me installer and perform installation steps
  any_errors_fatal: true
  import_playbook: playbooks/depenguin-install.yml

- name: Connect to rescue system and reboot
  any_errors_fatal: false
  import_playbook: playbooks/exit-rescue.yml

#- name: Local pause to wait for server boot
#  any_errors_fatal: true
#  import_playbook: playbooks/local-wait.yml

- name: Connect to resulting BSD host and perform upgrades
  any_errors_fatal: true
  import_playbook: playbooks/live-system.yml

