---

- name: Upgrade FreeBSD packages
  become: yes
  become_user: root
  shell: pkg upgrade
  when: ansible_distribution == 'FreeBSD'
  register: result_pkg
  changed_when: "'Your packages are up to date' not in result_pkg.stdout"

- debug: var=result_pkg
  when: result_pkg.changed
