---

- name: Wait for port 22 to become open, wait for 2 seconds
  wait_for:
    port: 22
    delay: 2

- name: execute the depenguin.me installer
  become: yes
  become_user: root
  shell:
    cmd: |
      ./run.sh {{ depenguin_my_pub_key }} 

- name: Pause for 1 min to allow VM to start up
  ansible.builtin.pause:
    minutes: 1
