---

- name: Wait for port 22 to become open, wait for 2 seconds
  wait_for:
    port: 22
    delay: 2

- name: execute the depenguin.me installer
  become: yes
  become_user: root
  shell:
    cmd: |
      ./{{ depenguin_dl_filename }} {{ depenguin_my_pub_key }} 
  register: depenguinme_bg
  async: 1200
  poll: 0

# this pause is irritating
# we want to watch for output of async process to equal
#  Press CTRL-C to exit qemu
# then continue with next task

#- name: Pause for 180 second to allow VM to start up
#  ansible.builtin.pause:
#    seconds: 180

- name: "Pause for {{ wait_depenguin_boot_process }} seconds to allow the VM to boot up"
  wait_for:
    delay: "{{ wait_depenguin_boot_process }}"
    timeout: 0
