---

- name: "Sleep for {{ wait_depenguin_install_process }} seconds to let install finish"
  wait_for:
    delay: "{{ wait_depenguin_install_process }}"
    timeout: 0
  ignore_errors: true

- name: check if any running qemu virtual machines
  shell:
    cmd: |
      if [ -z $(pgrep qemu-system-x86_64) ]; then echo "success" > /tmp/qemu_is_exited; fi
  register: qemucheck
  until: qemucheck is succeeded
  retries: 2
  delay: 30
