---

- name: check if any running qemu virtual machines
  shell:
    cmd: |
      ps -ef | grep -c qemu-system-x86_64
  register: qemucheck
  until: qemucheck is succeeded
  retries: 10
  delay: 10
  when: qemucheck.rc == 0
