---

- name: Wait for port 22 to become open, wait for 2 seconds
  wait_for:
    port: 22
    delay: 2

- name: check if any running qemu virtual machines
  shell:
    cmd: |
      ps -ef | grep qemu-system-x86_64
  register: qemucheck
- debug: var=qemucheck
