---

# Click0 uses tmux for custom install script here:
# https://github.com/click0/ansible-freebsd-install-on-zfs-lite/blob/main/tasks/install_freebsd.yml
# 
# We do similar, and start installer in tmux session, then pass in the ENTER key to the named tmux session
# to get around the dialog box getting stuck with error message about zroot existing, and asking to press enter
#
# dialog --title ZFS Configuration --backtitle FreeBSD Installer --hline --ok-label Ok --no-cancel --inputbox zroot is already taken, please enter a name for the ZFS pool \011(Or confirm using the same name by just pressing enter) 8 80 zroot
#

# FreeBSD14 seems to want tmux commands run with 'sh -c' prefix for success else failures 
- name: Run the depenguin.me installer in tmux session
  become: yes
  become_user: root
  shell:
    chdir: /root
    cmd: |
      tmux new-session -d -s installer.0 "sh -c '/root/depenguin_bsdinstall.sh'"
  ignore_errors: false

# - name: Sleep for {{ wait_depenguin_install_process }} seconds and timeout
#   wait_for:
#     delay: "{{ wait_depenguin_install_process }}"
#     timeout: 0

# this might not be needed any more, retaining here for future use
#- name: Send zroot ENTER to tmux session to continue with zroot default
#  become: yes
#  become_user: root
#  shell:
#    chdir: /root
#    cmd: |
#      tmux send-keys -t installer.0 BSpace "zroot" ENTER
#  ignore_errors: false
