---

- name: Wait for port 1022 to become open, wait for 2 seconds
  wait_for:
    port: 1022
    delay: 2

- name: Run the depenguin.me installer
  become: yes
  become_user: root
  shell:
    cmd: |
      /root/depenguin_bsdinstall.sh 
