---

- name: Run the depenguin.me installer
  become: yes
  become_user: root
  expect:
    chdir: /root
    command: ./depenguin_bsdinstall.sh
    responses:
      zroot: 'zroot'
    timeout: 600
    echo: yes
  ignore_errors: false
