---

- name: Wait for port 1022 to become open, wait for 2 seconds
  wait_for:
    port: 1022
    delay: 2
  ignore_errors: true

- name: Update packages
  raw: pkg update -f
  become: true
  become_user: root
  ignore_errors: true

- name: Update packages
  raw: ASSUME_ALWAYS_YES=yes pkg install python3
  become: true
  become_user: root
  ignore_errors: true