---

- name: Create depenguin_settings.sh file
  become: yes
  become_user: root
  copy:
    dest: /root/depenguin_settings.sh
    content: |
      #!/bin/sh
      conf_hostname="{{ conf_hostname }}"
      conf_interface="{{ conf_interface }}"
      conf_ipv4="{{ conf_ipv4 }}"
      conf_ipv6="{{ conf_ipv6 }}"
      conf_gateway="{{ conf_gateway }}"
      conf_nameserveripv4one="{{ conf_nameserveripv4one }}"
      conf_nameserveripv4two="{{ conf_nameserveripv4two }}"
      conf_nameserveripv6one="{{ conf_nameserveripv6one }}"
      conf_nameserveripv6two="{{ conf_nameserveripv6two }}"
      conf_username="{{ my_default_username }}"
      conf_pubkeyurl="{{ depenguin_my_pub_key }}"
      conf_disks="{{ conf_disks }}"
      conf_disktype="{{ conf_disktype }}"
      run_installer="{{ run_installer }}"

